"""add traceback to requests

Revision ID: 57dc4597c1ba
Revises: 1526872ac583
Create Date: 2014-01-16 14:28:43.985388

"""

# revision identifiers, used by Alembic.
revision = '57dc4597c1ba'
down_revision = '1526872ac583'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('traceback', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'traceback')
    ### end Alembic commands ###
